### ISSUE TITLE
Add the ability to provide custom dates to disable.

### ISSUE THREAD

**Issue by hasanmhallak** [hasanmhallak/date_picker#1]

**Comment by hasanmhallak** [comment]
I am considering the implementation of a disabled day predicate that would be executed for each day within the specified range. This approach provides greater flexibility in incorporating complex logic compared to simply providing a list of disabled days.

Here's an example usage of the disabled day predicate:

```dart
disabledDayPredicate: (date) {
    // This callback will be executed for each date.
    // Return false to keep the date enabled.
    // Return true to disable the day.
},
```

Furthermore, utilizing the disabled day predicate offers us the flexibility to incorporate custom logic aligned with our business rules. This enables us to disable specific days based on our defined criteria. For instance, if we wish to disable weekends, we can simply implement the following logic:

```dart
disabledDayPredicate: (date) {
    // This will disable every Sunday and Monday.
    return date.weekday == DateTime.sunday || date.weekday == DateTime.monday;
},
```  
Or even define elsewhere.
```dart
disabledDayPredicate: myCustomPredicate,
```

By adopting this approach, we can tailor the behavior of our date picker to meet our specific requirements, providing a more adaptable and customizable solution.

**Comment by LuisRobertoNavarro** [comment]
Excelente paquete, y lo voy a implementar en mis app's. Lo único que no veo es la posibilidad de poner un título y los botones de aceptar y cancelar. Muchas gracias

**Comment by avatarnguyen** [comment]
@hasanmhallak really like the idea as it would give the widget more flexibility.
What do you think about also adding callback to other styling parameter as well?

**Comment by hasanmhallak** [comment]
hey @avatarnguyen, I'm not sure about adding this callback for the styling as there is a parameter for almost all the styles.

Do you a use case for this? I would love to see what you have in mind. If you are willing to provide an example for the use case please open another issue with an example as I'm closing this as completed.
