### ISSUE TITLE
Add option custom ui date picker

### ISSUE THREAD

**Issue by chuvanhoang888** [hasanmhallak/date_picker#10]
Hello Sir,
This is a great package, but can you add option customize the date range picker interface as below?
![Screenshot 2024-01-10 at 13 56 00](https://github.com/hasanmhallak/date_picker/assets/104492264/b69c5f54-54fe-4491-aa19-bad4435d0051)
In my case, I need  date range picker that returns the same start day and end day when double clicked on the same day

**Comment by hasanmhallak** [comment]
hey @chuvanhoang888, I add the ability to select the same date as a range, and to center the leading date as your image shows.

Unfortunately there is no possible way to customize the look of the page sliders without changing a lot of code which I don't have the time for it. But I open to review any pull requests.
