### ISSUE TITLE
`singelSelectedCellTextStyle` is misspelt

### ISSUE THREAD

**Issue by LiamHod** [hasanmhallak/date_picker#13]
Both disbaledCellsTextStyle and disbaledCellsDecoration contain the word disbaled which should be changed to disabled.

**Comment by hasanmhallak** [comment]
hey @LiamHod. Thank you for opening this issue. I will fix the typos in the next release

**Comment by coogle** [comment]
Same for `singelSelectedCellTextStyle` which is misspelled :)

**Comment by hasanmhallak** [comment]
hey @coogle, I'm sorry I missed your comment, I guess I'll reopen this issue until another breaking change happens so I can fix the `singelSelectedCellTextStyle`. Sorry for the inconvenience :(
