### ISSUE TITLE
bro, picker in landscape is bottom overflowed

### ISSUE THREAD

**Issue by benjamini258369gmail** [hasanmhallak/date_picker#20]

**Comment by hasanmhallak** [comment]
could you elaborate more? and maybe share a reproducible example?

**Comment by becjit** [comment]
https://github.com/hasanmhallak/date_picker/assets/2213422/2cb36117-0ef6-43fb-840d-17eb7ce17aad


May be he is talking about this?

**Comment by hasanmhallak** [comment]
this should be fixed now in latest release. Please read the changelog before upgrading.
