### ISSUE TITLE
Setting first day of week?

### ISSUE THREAD

**Issue by thetobyde** [hasanmhallak/date_picker#27]
Can you tell the DatePicker to use Mon as first day of the week? :)

**Comment by hasanmhallak** [comment]
hey @thetobyde you can set it by setting the locale of your app to one that start the week on Mon like 'en_US' if I recall correctly.
However, if you don't want to change you whole app locale, you can override the locale above the datePicker widget and use a builder to provide a new context. This way the picker look up the locale using the new provided context it will use the first week day accordingly. If you want to change it in the `showDatePickerDialog` you will have to pass a context that has the right locale for it.
