### ISSUE TITLE
feat: Add Range Date Picker

### ISSUE THREAD

**Issue by chuvanhoang888** [hasanmhallak/date_picker#7]
hello, does this package support date range picker.

**Comment by hasanmhallak** [comment]
hey @chuvanhoang888, thank you for open this issue. I'm working on this feature already, it should be ready for release next week.

**Comment by chuvanhoang888** [comment]
Awesome, thanks for the update!

Vào 15:56, Th 3, 28 thg 11, 2023 Hasan M. Hallak ***@***.***>
đã viết:
